; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.1.4-LPC-5 on Fri Oct 16 2020 12:11:40 GMT+0200 (Central European Summer Time)
; Wait for set temperatures to be reached
M116 P0

